In [3]:
import numpy as np

In [4]:
a = np.array([[2,4,6],[1,3,5],[22,33,45],[44,64,54]])

In [5]:
a

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [22, 33, 45],
       [44, 64, 54]])

In [6]:
print(a.ndim)

2


In [7]:
print(a[0])

[2 4 6]


In [8]:
a[0]

array([2, 4, 6])

In [9]:
a[2]

array([22, 33, 45])

In [10]:
a[-2]

array([22, 33, 45])

In [11]:
a[3,0]

44

In [12]:
a[3]

array([44, 64, 54])

In [13]:
x=a[3]

In [14]:
x[0]

44

In [15]:
a

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [22, 33, 45],
       [44, 64, 54]])

In [16]:
1:3

SyntaxError: illegal target for annotation (<ipython-input-16-354ff4bd3bf9>, line 1)

In [17]:
a[1:3] 

array([[ 1,  3,  5],
       [22, 33, 45]])

In [18]:
a[:,1:]

array([[ 4,  6],
       [ 3,  5],
       [33, 45],
       [64, 54]])

In [19]:
a[:2,1:]

array([[4, 6],
       [3, 5]])

In [20]:
a[:,1:]

array([[ 4,  6],
       [ 3,  5],
       [33, 45],
       [64, 54]])

In [21]:
a

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [22, 33, 45],
       [44, 64, 54]])

In [22]:
a[:1]

array([[2, 4, 6]])

In [23]:
a[:,1:2]

array([[ 4],
       [ 3],
       [33],
       [64]])

In [25]:
#trigo

In [26]:
a = np.array([0,30,60,90,120,150,180])

In [31]:
s=np.sin(a*np.pi/180)

In [32]:
cosec = np.arcsin(s)
cosec

array([0.00000000e+00, 5.23598776e-01, 1.04719755e+00, 1.57079633e+00,
       1.04719755e+00, 5.23598776e-01, 1.22464680e-16])

In [33]:
np.degrees(cosec)

array([0.0000000e+00, 3.0000000e+01, 6.0000000e+01, 9.0000000e+01,
       6.0000000e+01, 3.0000000e+01, 7.0167093e-15])

In [35]:
ar = np.array([12.202,90.23210,123.020,23.202])
np.floor(ar)

array([ 12.,  90., 123.,  23.])

In [36]:
np.ceil(ar)

array([ 13.,  91., 124.,  24.])

In [38]:
s = np.array([[2,10,20],[23,54,77],[32,54,88]])

In [40]:
s

array([[ 2, 10, 20],
       [23, 54, 77],
       [32, 54, 88]])

In [41]:
s

array([[ 2, 10, 20],
       [23, 54, 77],
       [32, 54, 88]])

In [42]:
np.amin(s)

2

In [43]:
np.max(s)

88

In [44]:
np.median(s)

32.0

In [45]:
np.mean(s)

40.0

In [46]:
np.average(s)

40.0